[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cytofstandard"
version = "0.2.0"
description = "Standard CyTOF analysis package"
requires-python = ">=3.10"
dependencies = [
  "anndata",
  "zarr",
  "numpy",
  "pandas",
  "matplotlib",
  "seaborn",
  "pyarrow",
  "pyyaml",
  "xxhash",
  "tqdm",
  "fcsparser",
  "flowsom",
  "vendi-score",
  "umap-learn",
  "scikit-learn"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["cytofstandard*"]
